name: auto-update
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CACHIX_NAME: sigprof

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item:
          - pkgs/mozilla-langpack

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Install Nix
        uses: cachix/install-nix-action@92d36226ca2887d9bfe391bf2d00894d88be3b64
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ${{ env.CACHIX_NAME }}
          extraPullNames: "pre-commit-hooks"

      - name: Run the update script
        run: ${{ matrix.item }}/update.sh

      - name: Generate a GitHub token
        id: token
        uses: tibdex/github-app-token@v1.6.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create a PR
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ steps.token.outputs.token }}
          commit-message: "chore(${{ matrix.item }}): Automatic update"
          author: "sigprof[bot] <sigprof[bot]@users.noreply.github.com>"
          branch: "auto-update/${{ matrix.item }}"
          delete-branch: true
          title: "chore(${{ matrix.item }}): Automatic update"
          body: |
            Automatic update of `${{ matrix.item }}`.

            Generated by the [GitHub workflow run](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}).
          labels: "autorebase:opt-in"
